<Project>
	<PropertyGroup>
		<Authors>Mashiro Tamane</Authors>
		<Copyright>Copyright (c) 2026 $(Authors)</Copyright>
		<Version>$(VersionPrefix)$(VersionSuffix)</Version>
		<VersionPrefix>0.2.0</VersionPrefix>
		<VersionSuffix>preview.1</VersionSuffix>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>
</Project>